#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany 'pkg ensure $1' devel/auto{conf,gen,make} devel/libuuid devel/pkgconf

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y uuid-dev m4
      ;;
  esac

  mkdir -p "$shome/vendor"
  git clone git@github.com:firehol/netdata $shome/vendor/netdata-src || true
  pushd "$shome/vendor/netdata-src"
  git reset --hard
  git fetch
  git checkout "v${NETDATA_VERSION}"
  ./netdata-installer.sh --dont-wait --dont-start-it --install "$shome/vendor/netdata-${NETDATA_VERSION}"
  popd

  (cd "$shome/bin" && ln -nfs "../vendor/netdata-${NETDATA_VERSION}/netdata/usr/sbin/netdata" "$shome/bin/netdata")
}

bootstrap
