#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany 'pkg ensure $1' devel/auto{conf,gen,make} devel/libuuid devel/pkgconf devel/m4

  local pth_install="$shome/vendor/netdata-${NETDATA_VERSION}"

  if ! cache location "$pth_install"; then
    mkdir -p "$shome/vendor"
    git clone git@github.com:firehol/netdata $shome/vendor/netdata-src || true
    pushd "$shome/vendor/netdata-src"
    git reset --hard
    git fetch
    git checkout "v${NETDATA_VERSION}"
    ln -nfs $PKG_HOME/install/include/uuid
    ./netdata-installer.sh --dont-wait --dont-start-it --install "$pth_install"
    popd
    rm -rf "$shome/vendor/netdata-src"

    cache location archive "$pth_install"
  fi

  (cd "$shome/bin" && ln -nfs "$pth_install/netdata/usr/sbin/netdata" "$shome/bin/netdata")
}

bootstrap
