#!/usr/bin/env bash

function _netdata_profile {
  local shome="${_netdata_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  NETDATA_VERSION="1.6.0"
}

_netdata_profile
