#!/usr/bin/env bash

function server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      exec netdata -D
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

server "$@"
