#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_netdata="$(netdata -v 2>/dev/null | awk '{print $2}' || true)"
  jq -n --arg netdata "$ver_netdata" '{netdata: $netdata}'
}

version "$@"
